"""Add movies table

Revision ID: 4d2a33729281
Revises: 1771375af392
Create Date: 2023-10-17 11:57:33.526942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d2a33729281'
down_revision: Union[str, None] = '1771375af392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movies_id', table_name='movies')
    op.drop_index('ix_movies_name', table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('seen', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='movies_pkey')
    )
    op.create_index('ix_movies_name', 'movies', ['name'], unique=False)
    op.create_index('ix_movies_id', 'movies', ['id'], unique=False)
    # ### end Alembic commands ###
