"""Add watched_movies table

Revision ID: a4697516e4a4
Revises: ab920239a24f
Create Date: 2023-10-17 12:20:32.700874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4697516e4a4'
down_revision: Union[str, None] = 'ab920239a24f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watched_movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('watched_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watched_movies_id'), 'watched_movies', ['id'], unique=False)
    op.create_index(op.f('ix_watched_movies_title'), 'watched_movies', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watched_movies_title'), table_name='watched_movies')
    op.drop_index(op.f('ix_watched_movies_id'), table_name='watched_movies')
    op.drop_table('watched_movies')
    # ### end Alembic commands ###
